linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Fprint
      - (io.Writer).Write
      - (*text/tabwriter.Writer).Flush
